### ISSUE TITLE
Some error when interact with x-ray daemon

### ISSUE THREAD

**Issue by JerryZhao1988** [aws/aws-xray-sdk-python#109] opened 2018-10-11 05:55 UTC
I met some problems when  using flask middleware and x-ray daemon.
I try to set up a local test environment with flask application and x-ray deamon running in my docker env.

I met some error logs when start flask service. Based on error msg, it becomes a little bit confuse, do I need to start segment myself when using flask middleware. Or this error is introduced by patch_all().
```
{"asctime": "2018-10-11 05:35:32,469", "name": "aws_xray_sdk.core.context", "funcName": "handle_context_missing", "threadName": "MainThread", "levelname": "ERROR", "lineno": 120, "message": "cannot find the current segment/subsegment, please make sure you have a segment open"}
{"asctime": "2018-10-11 05:35:32,471", "name": "aws_xray_sdk.core.recorder", "funcName": "begin_subsegment", "threadName": "MainThread", "levelname": "WARNING", "lineno": 273, "message": "No segment found, cannot begin subsegment https://xxxx.com/xxx/xxx/xxxx."}
```

When a request reached my flask service, I would met the following error msg
```
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/rule_poller.py\", line 46, in _refresh_cache
    new_rules = self._connector.fetch_sampling_rules()
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/connector.py\", line 42, in wrapper
    result = func(self, *args, **kargs)
  File \"/usr/local/site-packages/aws_xray_sdk/core/sampling/connector.py\", line 56, in fetch_sampling_rules
    resp = self._xray_client.get_sampling_rules()
  File \"/usr/local/site-packages/botocore/client.py\", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File \"/usr/local/site-packages/wrapt/wrappers.py\", line 562, in __call__
    args, kwargs)
  File \"/usr/local/site-packages/aws_xray_sdk/ext/botocore/patch.py\", line 35, in _xray_traced_botocore
    return wrapped(*args, **kwargs)
  File \"/usr/local/site-packages/botocore/client.py\", line 610, in _make_api_call
    operation_model, request_dict)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 136, in _send_request
    success_response, exception):
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 205, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 228, in emit
    return self._emit(event_name, kwargs)
  File \"/usr/local/site-packages/botocore/hooks.py\", line 211, in _emit
    response = handler(**kwargs)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 251, in __call__
    caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 317, in __call__
    caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 223, in __call__
    attempt_number, caught_exception)
  File \"/usr/local/site-packages/botocore/retryhandler.py\", line 359, in _check_caught_exception
    raise caught_exception
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 174, in _get_response
    http_response = self._send(request)
  File \"/usr/local/site-packages/botocore/endpoint.py\", line 218, in _send
    return self.http_session.send(request)
  File \"/usr/local/site-packages/botocore/httpsession.py\", line 262, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: \"http://aws-xray-daemon:2000/GetSamplingRules\""}
```

I manual tested the x-ray deamon server, it can send x-ray records to AWS, but I would keep getting this kind of error logs in my flask server, which is not good for monitoring. 
I try to deploy all those stack in AWS ECS, still get the same error.

I added flask middleware like this:
```
xray_recorder.configure(
    service='xxx',
    sampling_rules=sampling_rule,
    context_missing='LOG_ERROR',
    plugins=('ECSPlugin',)
)
patch_all()
XRayMiddleware(app, xray_recorder)
```

My x-ray daemon running in another docker container with following dockerfile
```
FROM amazonlinux:2
RUN yum install -y unzip &&\
    curl -o daemon.zip https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-2.x.zip &&\
    unzip daemon.zip &&\
    cp xray /usr/bin/xray
ADD src/xray-daemon.entrypoint.sh /opt/xray-daemon.entrypoint.sh
ADD src/xray-daemon.cfg           /opt/xray-daemon.cfg
ENTRYPOINT ["/opt/xray-daemon.entrypoint.sh"]
```

xray-daemon.cfg
```
TotalBufferSizeMB: 128
Concurrency: 4
Region: xxxx
Socket:
  UDPAddress: "0.0.0.0:2000"
Logging:
  LogLevel: "error"
  LogPath: ""
LocalMode: true

ProxyAddress: "##PROXY_ADDRESS##"
Version: 1
```
entrypoint.sh 
```
#!/usr/bin/env bash
declare -r XRAY_DAEMON_CONF="/opt/xray-daemon.cfg"
declare -r CMD="/usr/bin/xray --bind 0.0.0.0:2000 -c ${XRAY_DAEMON_CONF}"
echo "### Starting Daemon with CMD [${CMD}] ###"
exec ${CMD}
```

docker-compose.yml
```
version: 2.1
services:
    flask-service:
        environment:
            AWS_XRAY_DAEMON_ADDRESS: 'aws-xray-daemon:2000'
        xxxx:
    aws-xray-daemon:
        environment:
            AWS_REGION: xxx
            AWS_DEFAULT_REGION: xxx
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
            AWS_SECURITY_TOKEN: ${AWS_SECURITY_TOKEN}
        command:
            - "/usr/bin/xray"
            - "--bind"
            - "0.0.0.0:2000"
            - "--region"
            - "xxx"
            - "--buffer-memory"
            - "64"
            - "--log-level"
            - dev
            - "--log-file"
            - "/dev/stdout"
```

dependency:
```
Flask==0.12.2

# x-ray
aws-xray-sdk==2.2.0
tox==3.4.0

boto==2.49.0
boto3==1.9.12
requests==2.18.4
```

**Comment by haotianw465** [comment] 2018-10-11 22:09
For the error on flask startup, if you patched http client or SQL client and during startup you are performing pre-fetching or schema validation which involves real http/sql outbound calls, it will cause issue since they are not tied to any particular request (no tracing context). You can either create segment manually on startup to wrap all traced operations so you can monitor the startup process, or you can set `AWS_XRAY_CONTEXT_MISSING` environment variable to `LOG_ERROR` so the subsegments for those operations will be dropped. After startup you don't need to manually create any segment as the flask middleware will emit one segment for every request/response cycle.

For the daemon communication issue the SDK 2.x requires X-Ray Daemon 3.x or later since only the newer versions of daemon listen to TCP traffic. The SDK use the daemon as the signing proxy to call public X-Ray API `GetSamplingRules` to fetch sampling rules from X-Ray service so you can change your sampling config on the flight. To lear more about this feature please see https://docs.aws.amazon.com/xray/latest/devguide/xray-console-sampling.html.

Please let me know if those answer your questions.

**Comment by JerryZhao1988** [comment] 2018-10-12 01:18
Hi haotian,

I updated the x-ray daemon version to version3
which is downloaded from https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
But I still get the same error message, do you have any ideas about it?


For the start up part question.
```
xray_recorder.configure(
    service='carbon-realtime',
    sampling_rules=sampling_rule,
    context_missing='LOG_ERROR',
    plugins=('ECSPlugin',)
)
patch_all()

log_handler = logging.StreamHandler()
log_formatter = jsonlogger.JsonFormatter(
    '%(asctime)s %(name)s %(funcName)s %(threadName)s %(levelname)s %(lineno)d %(message)s')
log_handler.setFormatter(log_formatter)
logger = logging.getLogger(__name__)

if os.environ.get('LOG_LEVEL'):
    logging.basicConfig(level=os.environ.get('LOG_LEVEL'), handlers=[log_handler])
else:
    logging.basicConfig(level=logging.ERROR, handlers=[log_handler])
```

I already set up the context_missing in xray_recorder.configure, for flask log level is also logging.ERROR, still get the same error msg...

**Comment by haotianw465** [comment] 2018-10-13 01:27
The log error for missing context is expected as the SDK emits this message to report there are operations suppose to be traced but the tracing data is dropped due to lack of context. If you only see it on startup, you don't need to worry about it if you are OK with not tracing the startup operations (http pre-fetching or SQL schema check etc).

For the daemon error, each account has a default sampling rule stored on X-Ray service. If the SDK fail to get the sampling rule back from daemon, it will use the local fallback rule which should not affect your application functionality.

Are you able to get any data on X-Ray console when running flask app (not manually testing daemon)? It's possible that in the daemon address you set `AWS_XRAY_DAEMON_ADDRESS: 'aws-xray-daemon:2000'`, the domain name `aws-xray-daemon` cannot be resolved in the container/ECS. The SDK sends data to the daemon over UDP and polls sampling rules via daemon over TCP. It would be helpful if we know whether none of these communication pass through or just the `GetSamplingRules ` call. It would also help if you can provide any debug level log entries emitted from the SDK.

**Comment by haotianw465** [comment] 2018-10-16 19:11
I understand that those log messages should be avoided. I will try to reproduce the `GetSamplingRules` on my end. For the cloudwatch error logs it is because the metrics flush is in a separate thread and it doesn't have any tracing context. This operation should be skipped. Do you have some code snippet of how you instantiate cloudwatch client and send metrics data?

**Comment by JerryZhao1988** [comment] 2018-10-22 02:26
We are using splunk instead of cloudwatch to monitor error logs... I didn't know how other stuff set it up...

is there any update on the GetSamplingRules problem?

**Comment by haotianw465** [comment] 2018-10-22 20:54
Hi @JerryZhao1988 , sorry for the late response. Based on the stack trace you posted, from this line `asctime: 2018-10-14 23:17:50,500, name: util.cloudwatch, funcName: flush_metrics, threadName: Thread-2, levelname: ERROR, lineno: 53` your application has a worker thread that calls `flush_metrics` to publish logs. If we can figure out where this thread comes from I can try to provide some workaround code to eliminate those error entries. In the long run the SDK should provide an option to become no-op for context missing.

For the `GetSamplingRules` problem I just realized that the daemon is still listening to `127.0.0.1:2000`  after closer look at the daemon startup logs posted: `2018-10-14T23:12:40Z [Info] Starting proxy http server on 127.0.0.1:2000`. `127.0.0.1` is a loopback and will not work on multi-container environment. It also needs to be binded to `0.0.0.0` similar to UDP. This is a new option `-t` introduced for daemon 3.x as it starts an extra http proxy comparing to 2.x. This is a miss on our end for documentation update. The daemon GitHub repo page is up-to-date with the new `-t` option https://github.com/aws/aws-xray-daemon but we also need to update https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html. Please let me know if this works for you.

**Comment by sebolabs** [comment] 2020-03-18 14:44
Hi. I'm having a similar issue...
I'm running x-ray daemon in a pod and have a service created that should expose it under the service name `xray-service` on port `2000`.
```
[Info] Initializing AWS X-Ray daemon 3.2.0
[Debug] Listening on UDP 0.0.0.0:2000
[Info] Using region: eu-west-1
[Debug] Using Endpoint: https://xray.eu-west-1.amazonaws.com
[Info] HTTP Proxy server using X-Ray Endpoint : https://xray.eu-west-1.amazonaws.com
[Info] Starting proxy http server on 0.0.0.0:2000
```

On my app configured with x-ray I'm getting:
```
botocore.exceptions.ConnectTimeoutError: Connect timeout on endpoint URL: http://xray-service:2000/GetSamplingRules
socket.timeout: timed out
```

From a busybox on the same cluster:
```
/ # nslookup xray-service
Server:    172.20.0.10
Address 1: 172.20.0.10 kube-dns.kube-system.svc.cluster.local

Name:      xray-service
Address 1: 10.175.27.86 10-175-27-86.xray-service.default.svc.cluster.local
/ # nc xray-service 2000 -v -w 3
nc: xray-service (10.175.27.86:2000): Connection timed out
```

Already tried with `127.0.0.1` and `0.0.0.0` but nothing works.
How should I configure it?

**Comment by shengxil** [comment] 2020-03-31 05:45
Hi @sebolabs,

The error looks like the x-ray pod's tcp 2000 port is not opened. Can you confirm if your Dockerfile has exposed the port? Please refer to https://docs.aws.amazon.com/xray/latest/devguide/xray-daemon-ecs.html to setup the daemon on container application.

**Closed** 2021-01-07 22:57 UTC
Labels: question
